spring:
  application:
    name: menu-x-backend
  profiles:
    active: dev

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: postgresql://postgres:007$he@M@db.fxxbzrxcakzbbdvxocsu.supabase.co:5432/postgres
    username: postgres
    password: 007$he@M
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Gemini AI Configuration
gemini:
  api:
    key: AIzaSyAuWkC4FLccs0EZs0prOufuBk2ojWaCb2E
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.menux: DEBUG
    org.springframework.security: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration for Production
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# Gemini AI Configuration for Production
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

# Server Configuration
server:
  port: ${PORT:8080}

# Logging
logging:
  level:
    com.menux: INFO
    org.springframework.security: WARN
